### ISSUE TITLE
UnicodeEncodeError while converting

### ISSUE THREAD

**Issue by thebaconing** [rrgeorge/FoundryToEncounter#5]
Converting folders
Converting journal
Converting playlists
Converting roll tables
Converting maps
Generating cover image
Traceback (most recent call last):
  File "foundrytoencounter.py", line 3352, in run
  File "foundrytoencounter.py", line 2651, in convert
  File "foundrytoencounter.py", line 1305, in createMap
  File "PIL\ImageDraw.py", line 497, in multiline_textsize
  File "PIL\ImageDraw.py", line 479, in textsize
  File "PIL\ImageFont.py", line 128, in getsize
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25bc' in position 0: ordinal not in range(256)

More Debug Data can be provided

**Comment by rrgeorge** [comment]
This is most likely a result of font dependency that’s not available. Can you send me the scenes.db?

**Comment by thebaconing** [comment]
[scenes.zip](https://github.com/rrgeorge/FoundryToEncounter/files/8091043/scenes.zip)
