### ISSUE TITLE
KeyError while converting

### ISSUE THREAD

**Issue by thebaconing** [rrgeorge/FoundryToEncounter#6]
Converting folders
Converting journal
Converting playlists
Converting roll tables
Converting maps
Generating cover image
Traceback (most recent call last):
  File "foundrytoencounter.py", line 3352, in run
  File "foundrytoencounter.py", line 2651, in convert
  File "foundrytoencounter.py", line 1112, in createMap
KeyError: 'name'

Additional debug info can be provided

**Comment by rrgeorge** [comment]
There’s a token without a name.

**Comment by thebaconing** [comment]
Thx
